### ISSUE TITLE
Python 3.7.8: "TypeError: Expected maxsize to be an integer or None" for lru_cache in line 780

### ISSUE THREAD

**Issue by MartinThoma** [OWASP/pytm#135]
```
$ pip install pytm
$ python pytm-example.py
Traceback (most recent call last):
  File "pytm-example.py", line 3, in <module>
    from pytm.pytm import TM, Server, Datastore, Dataflow, Boundary, Actor, Lambda
  File "/home/math/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pytm/__init__.py", line 3, in <module>
    from .pytm import Element, Server, ExternalEntity, Dataflow, Datastore, Actor, Process, SetOfProcesses, Boundary, TM, Action, Lambda, Threat, Classification, Data
  File "/home/math/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pytm/pytm.py", line 486, in <module>
    class TM():
  File "/home/math/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pytm/pytm.py", line 780, in TM
    @lru_cache
  File "/home/math/.pyenv/versions/3.7.8/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by nineinchnick** [comment]
Dup of #114, already fixed on Oct 2nd but we haven't yet released a version with that. @izar looks like it's time for 1.1.3

**Comment by MartinThoma** [comment]
In this case I'll close it :-)
